---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: rpk-client
  namespace: rpk-client
spec:
  dnsNames:
  - client.rampike.de
  issuerRef:
    kind: ClusterIssuer
    name: acme-staging
  secretName: rpk-client-certificate
